### ISSUE TITLE
Even more import/dependency errors

### ISSUE THREAD

**Issue by ywilke** [brennanaba/PLAbDab#4]
ImmuneBuilder is imported but not specified as an dependency.
Following the instructions from https://github.com/oxpig/ImmuneBuilder seems to work but when running plabdab I get.
```Traceback (most recent call last):
  File "/home/yawi/projects/vhh_search/plabdab.py", line 1, in <module>
    from PLAbDab import PLAbDab
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/PLAbDab/__init__.py", line 1, in <module>
    from PLAbDab.database import PLAbDab 
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/PLAbDab/database.py", line 7, in <module>
    from PLAbDab.structure_search import StructureSearch
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/PLAbDab/structure_search.py", line 3, in <module>
    from ImmuneBuilder import refine
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/ImmuneBuilder/__init__.py", line 1, in <module>
    from ImmuneBuilder.ABodyBuilder2 import ABodyBuilder2
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/ImmuneBuilder/ABodyBuilder2.py", line 8, in <module>
    from ImmuneBuilder.refine import refine
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/ImmuneBuilder/refine.py", line 1, in <module>
    import pdbfixer
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/pdbfixer/__init__.py", line 2, in <module>
    from .pdbfixer import PDBFixer
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/pdbfixer/pdbfixer.py", line 35, in <module>
    import openmm as mm
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/openmm/__init__.py", line 24, in <module>
    from openmm.openmm import *
  File "/home/useri/miniconda3/envs/test/lib/python3.8/site-packages/openmm/openmm.py", line 10, in <module>
    from . import _openmm
ImportError: /home/useri/miniconda3/envs/test/bin/../lib/libstdc++.so.6: version GLIBCXX_3.4.30 not found (required by /home/useri/miniconda3/envs/test/lib/python3.8/site-packages/openmm/../../../libOpenMM.so.8.0)
```

Is there a docker that has all the dependencies to run PLAbDab because it is very difficult to get it running.
Otherwise adding some instructions would be nice.

**Comment by brennanaba** [comment]
Hi @ywilke 

Thanks again for spotting this. I have added some installation instructions.

Basically, PLAbDab depends on ImmuneBuilder which depends on a bunch of packages that are either not currently available via pip (anarci, openmm) or have multiple versions depending on your machine (pytorch). This is my reason for leaving them out of the setup.py. There are some installation instructions on the ImmuneBuilder repo that should guide you through this. 

All the best,

Brennan
